export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const SEND_SOLDIERS = "SEND_SOLDIERS"
export const MAKE_READY_FOR_BATTLE = "MAKE_READY_FOR_BATTLE"
export const MAKE_READY_FOR_NEXT_TURN = "MAKE_READY_FOR_NEXT_TURN"
export const RESET_READY = "RESET_READY"

export const SET_OPPONENT = "SET_OPPONENT"

export const SET_GAME = "SET_GAME"

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_GAME_SCREEN_PAGE = "SET_GAME_SCREEN_PAGE"
export const SET_UPDATE_MESSAGE = "SET_UPDATE_MESSAGE"
export const SET_NEXT_STEP = "SET_NEXT_STEP"
